# Generated by Django 3.1.7 on 2021-04-28 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='clgname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='mobile',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
