# Generated by Django 3.1.7 on 2021-05-02 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_app', '0004_auto_20210502_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedes',
            name='course_name',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='CourseName',
        ),
    ]
