# Generated by Django 3.1.7 on 2021-05-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_app', '0005_auto_20210502_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedes',
            name='course_price',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='coursedes',
            name='course_des',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='coursedes',
            name='course_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
