# Generated by Django 3.1.7 on 2021-05-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_app', '0007_regcourses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regcourses',
            name='course_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='regcourses',
            name='user_name',
            field=models.CharField(max_length=100),
        ),
    ]
